### PR TITLE
Show "Add a Professor" link on empty search results

### LINKED ISSUE #31: Show link to add professor when professor search list is empty
When searching for a professor returns no results, we just say "no results found." 
image

Instead, we should add some message with a link or button to the effect of "we couldn't find that professor, would you like to add them?"

### PR DESCRIPTION
**Pull request by Chris2fourlaw**
- Fixes #31
- Includes updated package-lock.json
- Remove trailing whitespace
- Remove whitespace on Add a Professor navbar

Screen Shot 2022-08-02 at 11 26 25 PM

### CODE REVIEW

**Comment by mfish33** [comment]
Looks pretty good. What do you think about stacking one on top of the other, center-aligned without the period?

Like:
No Results Found
Add a professor?

**Comment by Chris2fourlaw** [comment]
Is this better?
image

**Comment by mfish33** [comment]
This looks great! 🎉

**Comment by Chris2fourlaw** [comment]
Oh shoot I didn’t push this commit yet

**Comment by mfish33** [comment]
Just add the commit to the beta branch. We will then squash into master

**Pull request merged**
