### PR TITLE
Professor Route change

### PR DESCRIPTION
**Pull request by mfish33**
This changes the route for all professor from /teacher/:id to /professor/:id

Ex:
From: https://polyratings.dev/teacher/0909a8a9-f5f2-4326-98d4-c14520dd1dd0
To: https://polyratings.dev/professor/0909a8a9-f5f2-4326-98d4-c14520dd1dd0

### CODE REVIEW

**Comment by mfish33** [comment]
@AddisonTustin I'll let you merge this and push it up through beta to prod. This is so that you can invalidate the crawling data

**Comment by AddisonTustin** [comment]
Might want to reconsider changing from `TeacherCard` to `ProfessorCard`, but can try for that in the future.

**Review by AddisonTustin — APPROVED** [review]
Might want to reconsider changing from `TeacherCard` to `ProfessorCard`, but can try for that in the future.

**Comment by AddisonTustin** [comment]
Successful manual tests in beta:
https://beta.polyratings.dev/professor/82ea81aa-9eea-49a2-aa91-e6c50712b592
https://beta.polyratings.dev/professor/b0ac90b7-b661-46d8-8b47-eec663230995
https://beta.polyratings.dev/professor/f6449c6d-0812-4008-b75b-6b7227674cef

**Comment by mfish33** [comment]
> Might want to reconsider changing from `TeacherCard` to `ProfessorCard`, but can try for that in the future.

Yes, there is definitely some clean-up to be done. At least that change does not affect anything public facing

**Pull request merged**
