### PR TITLE
CI/CD Improvements, Type Fix, and Not found search link

### LINKED ISSUE #31: Show link to add professor when professor search list is empty
When searching for a professor returns no results, we just say "no results found." 
image

Instead, we should add some message with a link or button to the effect of "we couldn't find that professor, would you like to add them?"

### PR DESCRIPTION
**Pull request by mfish33**
Closes #31

### CODE REVIEW

**Comment by Chris2fourlaw** [comment]
> ## Deploying with  [Cloudflare Pages](https://pages.dev)  Cloudflare Pages
> **Latest commit:**	`8baa276`
> **Status:**	 ✅  Deploy successful!
> **Preview URL:**	https://8fd55137.polyratings.pages.dev
> **Branch Preview URL:**	https://beta.polyratings.pages.dev
> [View logs](https://dash.cloudflare.com/?to=/:account/pages/view/polyratings/8fd55137-0f1f-455d-8684-ac88612f62c6)

Yikes

**Review by Chris2fourlaw — APPROVED** [review]
Let’s see if we can do a follow up to make sure PRs skip deployment

**Review by Chris2fourlaw — CHANGES_REQUESTED** [review]
See #56

**Comment by mfish33** [comment]
> Let’s see if we can do a follow up to make sure PRs skip deployment

This is as expected since this is merging from beta to master. Beta automatically deploys to the beta environment. Our current workflow is `feature_branch -> beta -> master`

**Review by Chris2fourlaw — APPROVED** [review]

**Comment by Chris2fourlaw** [comment]
@mfish33 ready for merge

**Comment by mfish33** [comment]
Congrats 🎉 🎉 . Thank you for your contributions, they should be live on the website shortly

**Pull request merged**
